### ISSUE TITLE
Cannot get Globals

### ISSUE THREAD

**Issue by mindmergedesign** [aryehraber/statamic-fetch#22]
I have installed fetch on my site. I am able to access all the url endpoints (pages and collections) but I get an error when I enter the globals endpoint. /!/Fetch/globals
```
Whoops, looks like something went wrong.
```

**Comment by aryehraber** [comment]
Hey @mindmergedesign, thanks for reporting your issue. Any chance you can dig up the full log + stack trace?

**Comment by mindmergedesign** [comment]
@aryehraber Here is the stack trace. Thanks for looking into this. This is an amazing addon!
```
Last login: Sat Oct 13 17:02:32 on ttys000
ssh forge@198.74.57.92
 juan@Juans-MBP  ~/Sites  ssh forge@198.74.57.92
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.17.17-x86_64-linode116 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
  GNU nano 2.5.3         File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Ad$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicCo$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicCo$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controlle$
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Il$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Ro$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Il$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{clo$
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Il$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Il$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Il$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Il$
                               [ Read 372 lines ]
^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C Cur Pos
^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line
  GNU nano 2.5.3          File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Add$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicCon$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicCon$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controller$
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illu$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Rou$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{clos$
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Ill$

^G Get Help  ^O Write Out ^W Where Is  ^K Cut Text  ^J Justify   ^C Cur Pos
^X Exit      ^R Read File ^\ Replace   ^U Uncut Text^T To Spell  ^_ Go To Line
  GNU nano 2.5.3                  File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController:$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illumina$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerD$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illu$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Htt$
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php($

^G Get Help    ^O Write Out   ^W Where Is    ^K Cut Text    ^J Justify     ^C Cur Pos     ^Y Prev Page
^X Exit        ^R Read File   ^\ Replace     ^U Uncut Text  ^T To Spell    ^_ Go To Line  ^V Next Page
  GNU nano 2.5.3                     File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlo$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(55$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(53$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(50$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(60$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(50$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Cont$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Co$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatch$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatc$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Reque$
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatc$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatc$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): I$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page
  GNU nano 2.5.3                     File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlob$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(556$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(536$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(505$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Conta$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Con$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256)$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatche$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatch$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\H$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139)$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Reques$
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102)$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatch$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatch$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Il$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page
  GNU nano 2.5.3                      File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlobals$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(556): $
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(536): $
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(505): $
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604): $
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): $
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Containe$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Contro$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): c$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.p$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): c$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): c$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illum$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page
  GNU nano 2.5.3                       File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlobals() d$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(556): Refl$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(536): Illu$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(505): Illu$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604): Illu$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): Illu$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Container\Co$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Controller$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(1$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php($
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Req$
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php($
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php($
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminat$

^G Get Help    ^O Write Out   ^W Where Is    ^K Cut Text    ^J Justify     ^C Cur Pos     ^Y Prev Page   M-\ First Line
^X Exit        ^R Read File   ^\ Replace     ^U Uncut Text  ^T To Spell    ^_ Go To Line  ^V Next Page   M-/ Last Line
  GNU nano 2.5.3                            File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlobals() does not exist$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(556): ReflectionMethod-$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(536): Illuminate\Contai$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(505): Illuminate\Contai$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604): Illuminate\Contai$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): Illuminate\Contai$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Container\Container->call$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Controllers\StatamicCon$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_arr$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illumina$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illumin$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Obj$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Obj$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illumin$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illumina$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\Con$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page    M-\ First Line
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page    M-/ Last Line
  GNU nano 2.5.3                               File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlobals() does not exist in /home/$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(556): ReflectionMethod->__constru$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(536): Illuminate\Container\Contai$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(505): Illuminate\Container\Contai$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604): Illuminate\Container\Contai$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): Illuminate\Container\Contai$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Container\Container->call('Statamic$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Controllers\StatamicController->c$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, $
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routin$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closur$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closur$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeli$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDis$

^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page    M-\ First Line  M-W WhereIs Next
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page    M-/ Last Line   M-] To Bracket
  GNU nano 2.5.3                               File: statamic-2018-10-16.log

[2018-10-16 18:32:11] production.ERROR: ReflectionException: Method Statamic\Addons\Fetch\FetchController::getGlobals() does not exist in /home/f$
Stack trace:
#0 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(556): ReflectionMethod->__construc$
#1 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(536): Illuminate\Container\Contain$
#2 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(505): Illuminate\Container\Contain$
#3 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(604): Illuminate\Container\Contain$
#4 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): Illuminate\Container\Contain$
#5 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(123): Illuminate\Container\Container->call('Statamic\$
#6 /home/forge/apicswlegal.mmddev.net/statamic/core/Http/Controllers/StatamicController.php(93): Statamic\Http\Controllers\StatamicController->ca$
#7 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Fetch', 'globals')
#8 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, A$
#9 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\$
#10 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing$
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure$
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure$
#15 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipelin$
#16 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\$
#17 /home/forge/apicswlegal.mmddev.net/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDisp$
```

**Comment by aryehraber** [comment]
Hmm, from the stack trace it seems `globals` aren't available. Can you confirm you are on the latest version of Fetch?

https://statamic.com/marketplace/addons/fetch

**Comment by mindmergedesign** [comment]
@aryehraber that was the issue! I had an older version installed (2.1). Everything is working now. Thanks again for the help and for such a nice addon. It works great!
